backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "global"
      name: "global"
      file: "content/global.md"
      fields:
        - label: 'Title'
          name: 'title'
          widget: 'string'
        - label: 'Image'
          name: 'image'
          widget: 'image'
        - label: "Social"
          name: "social"
          widget: "list"
          collapsed: true
          fields: 
            - label: "Name"
              name: "name"
              widget: "string"
            - label: "Link"
              name: "link"
              widget: "string"
        - label: "Navigation"
          name: "navigation"
          widget: "list"
          collapsed: true
          fields: 
            - label: "Name"
              name: "name"
              widget: "string"
            - label: "Links"
              name: "links"
              widget: "list"
              collapsed: true
              fields: 
              - label: "Name"
                name: "name"
                widget: "string"
              - label: "Link"
                name: "link"
                widget: "string"
              - label: "Icon"
                name: "icon"
                widget: "string"
              - label: "Is external"
                name: "isExternal"
                widget: "boolean"
                required: false
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    fields: 
      - label: "Title"
        name: "title"
        widget: "string"
        required: true
      - label: "Tags"
        name: "tags"
        widget: "select"
        multiple: true
        max: 3
        options: [
          "Javascript",
          "HTML",
          "CSS",
          "Vue.js",
          "React",
          "Nextjs",
          "Web Performance",
          "Life style",
          "Productivity",
          "CMS",
          "JamStack",
          "Frontend",
          "Serverless",
          "Experiments"
        ]
      - label: "Card Image"
        name: "cardImage"
        widget: "image"
      - label: "Description"
        name: "description"
        widget: "text"
        required: true
      - label: "Created at"
        name: "createdAt"
        widget: "date"
        date_format: "DD/MMM/YYYY"
        format: "MMM DD, YYYY"
      - label: "Read time"
        name: "readTime"
        widget: "number"
        value_type: "int"
      - label: "Body"
        name: "body"
        widget: "markdown"
          