backend:
  # name: test-repo
  name: git-gateway
  # Branch to update (optional; defaults to master)
  branch: feature/netlify-cms
  # branch: master
media_folder: public/img
public_folder: img
media_library:
  name: cloudinary
  config:
    cloud_name: dzgf40ghh
    api_key: 958272413457741
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Meta Title", name: "metaTitle", widget: "string" }
        - { label: "Meta Description", name: "metaDescription", widget: "text" }
        - { label: "Meta Image", name: "metaImage", widget: "image" }
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "markdown" }
        - label: 'Jobs'
          name: "jobs"
          widget: list
          fields:
            - { label: "Company", name: "company", widget: "string"}
            - { label: "Position", name: "position", widget: "string", default: 'Frontend Developer'}
            - { label: "Start date", name: "startDate", widget: "date" }
            - { label: "End date", name: "endDate", widget: "date" }
            - { label: "Is Actual", name: 'isActual', widget: "boolean", default: false }
            - { label: "Image",  name: "image", widget: "image",allow_multiple: false }